// this is mock-data actual data should come out of cms
export const users = [
  {
    id:'1',
    first_name:'Joost',
    last_name: 'Hermans',
    username: 'wizzard93',
    nickname: 'Champ',
    role: 'admin',
    goals: [],
    achievements_done: [], 
    workouts_done: [], 
    workout_current: [], 
    workout_planned: [],
  },
  {
    id:'2',
    first_name:'Erick',
    last_name: 'Spoelstra',
    username: 'miami_heat_forever',
    nickname: 'Goat',
    role: 'coach',
    goals: [],
    achievements_done: [], 
    workouts_done: [], 
    workout_current: [], 
    workout_planned: [],
  },
  {
    id:'3',
    first_name:'Karen',
    last_name: 'complains',
    username: 'negativenelly2',
    nickname: 'Cupcake',
    role: 'sporter',
    goals: [],
    achievements_done: [], 
    workouts_done: [], 
    workout_current: [], 
    workout_planned: [],
  },
]
